volumes:
    dataquality-postgres:
        driver: local

services:
  dataquality-postgres:
    image: postgres:16.3
    container_name: dataquality-postgres
    env_file:
      - .env.postgres
    networks:
      - dataquality-network
    volumes:
        - dataquality-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dataquality-back:
    image: 249258753394.dkr.ecr.eu-west-3.amazonaws.com/ntico/data-quality/back:latest
    container_name: dataquality-back
    env_file:
      - .env.back
    depends_on:
      - dataquality-postgres
    networks:
      - dataquality-network
    volumes:
      - ./known_hosts:/app/known_hosts
      - ./security:/app/security
    ports:
      - "8081:8081"
      
  dataquality-avro:
    image: 249258753394.dkr.ecr.eu-west-3.amazonaws.com/ntico/data-quality/avro:latest
    container_name: dataquality-avro
    env_file:
      - .env.avro
    networks:
      - dataquality-network
    volumes:
      - ./known_hosts:/app/known_hosts
    ports:
      - "8083:8083"
      
  dataquality-integrator:
    image: 249258753394.dkr.ecr.eu-west-3.amazonaws.com/ntico/data-quality/integrator:latest
    container_name: dataquality-integrator
    env_file:
      - .env.integrator
    depends_on:
      - dataquality-avro
    networks:
      - dataquality-network
    volumes:
      - ./known_hosts:/app/known_hosts
    ports:
      - "8082:8082"
      
  dataquality-front:
    image: 249258753394.dkr.ecr.eu-west-3.amazonaws.com/ntico/data-quality/front:latest
    container_name: dataquality-front
    depends_on:
      - dataquality-back
    volumes:
      - ./specific:/usr/share/nginx/html/specific
      - ./specific_http/nginx.conf:/etc/nginx/nginx.conf
      - ./certificate:/etc/nginx/ssl:ro
    networks:
      - dataquality-network
    ports:
      - "443:443"

networks:
  dataquality-network:
    driver: bridge